# Generated by Django 4.1.1 on 2022-09-06 21:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('biografia', models.TextField()),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('numero', models.IntegerField(default=1, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(1)])),
                ('editorial', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Linguagem', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('introducao', models.TextField()),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCRUD.autor')),
                ('eicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCRUD.edicao')),
                ('linguagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCRUD.linguagem')),
            ],
        ),
    ]
